// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwqx7OlNDA_-YDGjGcPDG3x_pC2sTxyBQ',
    appId: '1:1046796118200:web:56295046b28265396aac4d',
    messagingSenderId: '1046796118200',
    projectId: 'flutterbloc-8bd9b',
    authDomain: 'flutterbloc-8bd9b.firebaseapp.com',
    storageBucket: 'flutterbloc-8bd9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFpwKD2bRran28aVSgwdcbRLBmwwqX3qA',
    appId: '1:1046796118200:android:1457fbf9118ea3126aac4d',
    messagingSenderId: '1046796118200',
    projectId: 'flutterbloc-8bd9b',
    storageBucket: 'flutterbloc-8bd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6PGvoWHe18HMzqMnNbyakcnQAhGY7V84',
    appId: '1:1046796118200:ios:92f351c4585188456aac4d',
    messagingSenderId: '1046796118200',
    projectId: 'flutterbloc-8bd9b',
    storageBucket: 'flutterbloc-8bd9b.appspot.com',
    iosClientId: '1046796118200-90p8v6t0g2h978nv9tb8v0f21pga1358.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6PGvoWHe18HMzqMnNbyakcnQAhGY7V84',
    appId: '1:1046796118200:ios:a5390080807f671f6aac4d',
    messagingSenderId: '1046796118200',
    projectId: 'flutterbloc-8bd9b',
    storageBucket: 'flutterbloc-8bd9b.appspot.com',
    iosClientId: '1046796118200-qkue7fi4nk07r5kard0tdolbmclapih5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBloc.RunnerTests',
  );
}
